### PR TITLE
feat: Added code to calculate Search Ads 360 net conversions

### PR DESCRIPTION
**Pull request by leviorca**
The solution pulls conversions from SA360 using Google Search Ads API and uploads a copy to a new floodlight activity with a new revenue calculated deducting internal costs.
[Profitable_Sales _SA360_GCP_Automation.pdf](https://github.com/google/orchestra/files/5217601/Profitable_Sales._SA360_GCP_Automation.pdf)

### CODE REVIEW

**Comment by leviorca** [comment]
@googlebot I signed it!

**Comment by mik-laj** [comment]
Hello.
Have you thought about passing these operators to Apache? In the next step, they will be available as a [backport package/provider package](https://github.com/apache/airflow#backport-packages), and these packages are [installed by default](https://cloud.google.com/composer/docs/release-notes#August_03_2020) in the Cloud Composer environment. This will significantly facilitate and promote their use. 
If you are interested, I will be happy to help.

**Comment by leviorca** [comment]
@googlebot I signed it!

**Comment by KingsleyKelly** [comment]
Thanks for this @leviorca. We will be adding a few comments this week.

@mik-laj thanks for the offer!

**Comment by KingsleyKelly** [comment]
LGTM to me. I believe the next step will be to refactor this to use more generic Airflow, however I don't think that's a blocker.

**Pull request merged**
